language: r
cache: packages
r:
  - oldrel
  - release
  - devel

sudo: false

warnings_are_errors: true

r_packages:
  - rmarkdown

r_check_args: --as-cran

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
